language: python
sudo: false
env:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - travis_retry conda create --yes -n qiita python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita
  - pip install sphinx==1.5.5 sphinx-bootstrap-theme coveralls
  - pip install https://github.com/biocore/qiita/archive/master.zip --process-dependency-links
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  - export MOI_CONFIG_FP=$HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg
  - qiita-env make --no-load-ontologies
  - source deactivate
  - travis_retry conda create --yes -n qiita_client python=$PYTHON_VERSION pip nose flake8 coverage
  - source activate qiita_client
  - travis_retry pip install .
before_script:
  - source activate qiita
  - qiita pet webserver --no-build-docs start &
script:
  - source activate env_name
  - sleep 5 # give enough time to the webserver to start
  - nosetests --with-doctest --with-coverage
  - flake8 qiita_client setup.py
addons:
    postgresql: "9.3"
services:
    - redis-server
    - postgresql
after_success:
  - coveralls
