language: python
sudo: false
env:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - travis_retry conda create --yes -n qiita_env python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita_env
  - pip install sphinx sphinx-bootstrap-theme coveralls ipython[all]==2.4.1
  - pip install https://github.com/biocore/qiita/archive/master.zip
  - ipython profile create qiita-general --parallel
  - qiita-env start_cluster qiita-general
  - qiita-env make --no-load-ontologies
  - export QIITA_SERVER_CERT=$PWD/qiita/qiita_core/support_files/server.crt
  - source deactivate
  - travis_retry conda create --yes -n env_name python=$PYTHON_VERSION pip nose flake8 httpretty coverage
  - source activate env_name
  - travis_retry pip install .
before_script:
  - source activate qiita_env
  - export MOI_CONFIG_FP=$HOME/miniconda3/envs/qiita_env/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg
  - ls -lh
  - which qiita
  - qiita pet webserver start
  - sleep 5
  - source activate env_name
script:
  - nosetests --with-doctest --with-coverage
  - flake8 qiita_client setup.py
addons:
    postgresql: "9.3"
services:
    - redis-server
    - postgresql
after_success:
  - coveralls
